# Generated by Django 5.1.5 on 2025-02-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicos',
            new_name='Servico',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='caro',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='servicos',
            new_name='servico',
        ),
    ]
